/* Auto-generated by genmsg_cpp for file /home/geovana/projects/hubo-ros/hubo_ros/msg/HuboHand.msg */
#ifndef HUBO_ROS_MESSAGE_HUBOHAND_H
#define HUBO_ROS_MESSAGE_HUBOHAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "hubo_ros/HuboJointState.h"
#include "hubo_ros/HuboJointState.h"
#include "hubo_ros/HuboJointState.h"
#include "hubo_ros/HuboJointState.h"
#include "hubo_ros/HuboJointState.h"

namespace hubo_ros
{
template <class ContainerAllocator>
struct HuboHand_ {
  typedef HuboHand_<ContainerAllocator> Type;

  HuboHand_()
  : thumb()
  , index()
  , middle()
  , ring()
  , pinky()
  {
  }

  HuboHand_(const ContainerAllocator& _alloc)
  : thumb(_alloc)
  , index(_alloc)
  , middle(_alloc)
  , ring(_alloc)
  , pinky(_alloc)
  {
  }

  typedef  ::hubo_ros::HuboJointState_<ContainerAllocator>  _thumb_type;
   ::hubo_ros::HuboJointState_<ContainerAllocator>  thumb;

  typedef  ::hubo_ros::HuboJointState_<ContainerAllocator>  _index_type;
   ::hubo_ros::HuboJointState_<ContainerAllocator>  index;

  typedef  ::hubo_ros::HuboJointState_<ContainerAllocator>  _middle_type;
   ::hubo_ros::HuboJointState_<ContainerAllocator>  middle;

  typedef  ::hubo_ros::HuboJointState_<ContainerAllocator>  _ring_type;
   ::hubo_ros::HuboJointState_<ContainerAllocator>  ring;

  typedef  ::hubo_ros::HuboJointState_<ContainerAllocator>  _pinky_type;
   ::hubo_ros::HuboJointState_<ContainerAllocator>  pinky;


  typedef boost::shared_ptr< ::hubo_ros::HuboHand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hubo_ros::HuboHand_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct HuboHand
typedef  ::hubo_ros::HuboHand_<std::allocator<void> > HuboHand;

typedef boost::shared_ptr< ::hubo_ros::HuboHand> HuboHandPtr;
typedef boost::shared_ptr< ::hubo_ros::HuboHand const> HuboHandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hubo_ros::HuboHand_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hubo_ros::HuboHand_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hubo_ros

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hubo_ros::HuboHand_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hubo_ros::HuboHand_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hubo_ros::HuboHand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dfd31cdc3f67d0c6f51804ccff860aaf";
  }

  static const char* value(const  ::hubo_ros::HuboHand_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdfd31cdc3f67d0c6ULL;
  static const uint64_t static_value2 = 0xf51804ccff860aafULL;
};

template<class ContainerAllocator>
struct DataType< ::hubo_ros::HuboHand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hubo_ros/HuboHand";
  }

  static const char* value(const  ::hubo_ros::HuboHand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hubo_ros::HuboHand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "HuboJointState thumb\n\
HuboJointState index\n\
HuboJointState middle\n\
HuboJointState ring\n\
HuboJointState pinky\n\
\n\
================================================================================\n\
MSG: hubo_ros/HuboJointState\n\
string name\n\
float64 commanded\n\
float64 position\n\
float64 velocity\n\
float64 current\n\
float64 temperature\n\
int32 active\n\
int32 zeroed\n\
\n\
";
  }

  static const char* value(const  ::hubo_ros::HuboHand_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hubo_ros::HuboHand_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.thumb);
    stream.next(m.index);
    stream.next(m.middle);
    stream.next(m.ring);
    stream.next(m.pinky);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct HuboHand_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hubo_ros::HuboHand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hubo_ros::HuboHand_<ContainerAllocator> & v) 
  {
    s << indent << "thumb: ";
s << std::endl;
    Printer< ::hubo_ros::HuboJointState_<ContainerAllocator> >::stream(s, indent + "  ", v.thumb);
    s << indent << "index: ";
s << std::endl;
    Printer< ::hubo_ros::HuboJointState_<ContainerAllocator> >::stream(s, indent + "  ", v.index);
    s << indent << "middle: ";
s << std::endl;
    Printer< ::hubo_ros::HuboJointState_<ContainerAllocator> >::stream(s, indent + "  ", v.middle);
    s << indent << "ring: ";
s << std::endl;
    Printer< ::hubo_ros::HuboJointState_<ContainerAllocator> >::stream(s, indent + "  ", v.ring);
    s << indent << "pinky: ";
s << std::endl;
    Printer< ::hubo_ros::HuboJointState_<ContainerAllocator> >::stream(s, indent + "  ", v.pinky);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HUBO_ROS_MESSAGE_HUBOHAND_H

